apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-configurations
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: 'https://git.anurajpd.com/anurajpd/oi-infra.git'
      revision: HEAD
      directories:
      - path: config/services/configurations/*
  template:
    metadata:
      name: '{{index .path.segments 3}}-config'
    spec:
      project: default
      source:
        repoURL: 'https://git.anurajpd.com/anurajpd/oi-infra.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
