apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - git:
      repoURL: https://git.anurajpd.com.com/anurajpd/oi-infra.git
      revision: HEAD
      directories:
      - path: config/services/operators/*/operator
  template:
    metadata:
      name: '{{index .path.segments 3}}-operator'
    spec:
      project: default
      source:
        repoURL: https://git.anurajpd.com.com/anurajpd/oi-infra.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
