apiVersion: v1
kind: Secret
metadata:
  name: image-registry-private-configuration-user
  namespace: openshift-image-registry
type: Opaque
data:
  REGISTRY_STORAGE_S3_ACCESSKEY:
  REGISTRY_STORAGE_S3_SECRETKEY: 
