apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powerflex
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  storagepool: SP01
  systemID: ad4fr345gfaa
  csi.storage.k8s.io/fstype: xfs
volumeBindingMode: Immediate
